apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: sensor
    name: sensor
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: sensor
    name: sensor
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: {}
    output:
      to:
        kind: ImageStreamTag
        name: sensor:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git: 
        uri: https://github.com/dsanchor/vertx-iot-workshop
        ref: master
# TODO add proper context dir (this is just for testing)
      contextDir: homeplan
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers: 
      - imageChange:
        type: ImageChange
      - type: ConfigChange
  status:
    lastVersion: 0
